name: flutter_architecture
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  surf_lint_rules: ^1.5.0

flutter:
  uses-material-design: true
